In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [6]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [7]:
# turn strings into ints | get_dummies()
# get_dummies
credit_ensemble = pd.get_dummies(df, columns = ["home_ownership", "verification_status", "loan_status", "pymnt_plan", "application_type", "hardship_flag", "debt_settlement_flag"])
credit_ensemble.head(10)

,loan_amnt,int_rate,installment,annual_inc,issue_d,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,loan_status_high_risk,loan_status_low_risk,pymnt_plan_n,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,Mar-2019,27.24,0.0,0.0,8.0,0.0,...,0,1,0,0,1,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,Mar-2019,20.23,0.0,0.0,17.0,1.0,...,0,0,1,0,1,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,Mar-2019,24.26,0.0,0.0,8.0,0.0,...,0,0,1,0,1,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,Mar-2019,31.44,0.0,1.0,10.0,1.0,...,0,0,1,0,1,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,Mar-2019,18.76,0.0,1.0,14.0,0.0,...,1,0,0,0,1,1,1,0,1,1
5,25000.0,0.1797,634.43,90000.0,Mar-2019,18.49,1.0,1.0,14.0,0.0,...,0,1,0,0,1,1,1,0,1,1
6,20400.0,0.2000,540.48,51315.0,Mar-2019,25.63,0.0,2.0,8.0,1.0,...,0,1,0,0,1,1,1,0,1,1
7,10000.0,0.1557,349.46,66000.0,Mar-2019,9.00,0.0,0.0,11.0,0.0,...,0,1,0,0,1,1,1,0,1,1
8,14000.0,0.0881,443.96,45000.0,Mar-2019,10.24,0.0,1.0,9.0,0.0,...,1,0,0,0,1,1,1,0,1,1
9,10000.0,0.1474,345.39,63295.0,Mar-2019,39.34,0.0,0.0,27.0,0.0,...,0,0,1,0,1,1,1,0,1,1

In [8]:
# Create our features
X = credit_ensemble.copy()
X = X.drop(columns=["loan_status_high_risk","issue_d","next_pymnt_d", "initial_list_status"], axis=1)


# Create our target
y = credit_ensemble["loan_status_high_risk"]

In [9]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,home_ownership_RENT,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,loan_status_low_risk,pymnt_plan_n,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.357659,0.478007,0.373992,0.148001,0.994958,1.0,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.479314,0.499520,0.483865,0.355104,0.070831,0.0,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,1.0,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,1.0,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,1.000000,1.000000,1.000000,0.000000,1.000000,1.0,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.0,1.0

In [10]:
# Check the balance of our target values
y.value_counts()

0    68470
1      347
Name: loan_status_high_risk, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

In [16]:
# # Scale 
# from sklearn.preprocessing import StandardScaler

# # Creating a StandardScaler instance.
# scaler = StandardScaler()
# # Fitting the Standard Scaler w/ training data.
# X_scaler = scaler.fit(X_train)

# # Scaling the data
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)

### Balanced Random Forest Classifier

In [30]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
brf_model = BalancedRandomForestClassifier(n_estimators=500, random_state=1)

brf_model = brf_model.fit(X_train, y_train)
brf_model

BalancedRandomForestClassifier(n_estimators=500, random_state=1)

In [26]:
# predictions = brf_model.predict(X_test)
# predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [31]:
y_pred = brf_model.predict(X_test)

In [32]:
# Display the confusion matrix

confusion_matrix(y_test, y_pred)

array([[17055,    49],
       [    0,   101]])

In [33]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

0.9985675865294668

In [34]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00     17104
          1       0.67      1.00      1.00      0.80      1.00      1.00       101

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     17205

In [35]:
# List the features sorted in descending order by feature importance
sorted(zip(brf_model.feature_importances_, X.columns), reverse=True)

[(0.41920424998929867, 'loan_status_low_risk'),
 (0.052836319248785596, 'last_pymnt_amnt'),
 (0.051291734893593316, 'total_rec_prncp'),
 (0.04175818727454345, 'total_rec_int'),
 (0.03967063139432953, 'total_pymnt'),
 (0.035784799864123105, 'total_pymnt_inv'),
 (0.02027090584531405, 'int_rate'),
 (0.01086507563683235, 'mths_since_recent_inq'),
 (0.010127504194114083, 'dti'),
 (0.009196223088991127, 'max_bal_bc'),
 (0.00919610656308153, 'annual_inc'),
 (0.0086511867097293, 'revol_bal'),
 (0.008512598555335645, 'installment'),
 (0.008478196935706235, 'out_prncp_inv'),
 (0.008323562315725471, 'tot_hi_cred_lim'),
 (0.008087376082041688, 'total_bc_limit'),
 (0.007950588456542734, 'avg_cur_bal'),
 (0.007878814883141507, 'out_prncp'),
 (0.007683916687496289, 'total_bal_il'),
 (0.007646001181328877, 'bc_open_to_buy'),
 (0.007630477620239131, 'mths_since_rcnt_il'),
 (0.007481717450788007, 'tot_cur_bal'),
 (0.007332118618118944, 'mo_sin_old_rev_tl_op'),
 (0.007141791267182867, 'mo_sin_old_il_acct'),
 (0.007129226845114932, 'total_rev_hi_lim'),
 (0.006879675227272856, 'total_rec_late_fee'),
 (0.006845431395244717, 'il_util'),
 (0.006799986252638178, 'total_bal_ex_mort'),
 (0.006631190288299671, 'total_il_high_credit_limit'),
 (0.006474030357919203, 'bc_util'),
 (0.006308731849527359, 'loan_amnt'),
 (0.006222401779037564, 'all_util'),
 (0.006211500996590285, 'total_acc'),
 (0.00592263026581732, 'mths_since_recent_bc'),
 (0.005812980479410173, 'mo_sin_rcnt_rev_tl_op'),
 (0.00574756290527192, 'inq_last_12m'),
 (0.005310851519304867, 'num_rev_accts'),
 (0.005290564538817482, 'num_op_rev_tl'),
 (0.005272259967664664, 'acc_open_past_24mths'),
 (0.005180135493659095, 'pct_tl_nvr_dlq'),
 (0.005136861535893794, 'mo_sin_rcnt_tl'),
 (0.005027845414962355, 'open_acc'),
 (0.0050208306178683194, 'num_il_tl'),
 (0.004884503943576992, 'open_il_24m'),
 (0.004848607568890883, 'num_tl_op_past_12m'),
 (0.004388375764102593, 'num_actv_bc_tl'),
 (0.004382009258796714, 'num_sats'),
 (0.004310163002556241, 'num_actv_rev_tl'),
 (0.004266882297387222, 'inq_fi'),
 (0.004257927942167072, 'num_bc_tl'),
 (0.00396089618580905, 'open_acc_6m'),
 (0.0038334330186614173, 'percent_bc_gt_75'),
 (0.0038072873523580693, 'num_rev_tl_bal_gt_0'),
 (0.003578679197210427, 'open_act_il'),
 (0.0035310786346365577, 'inq_last_6mths'),
 (0.003468129581690895, 'open_rv_24m'),
 (0.003411420826994456, 'total_cu_tl'),
 (0.003091514515591586, 'mort_acc'),
 (0.002966988325448291, 'num_bc_sats'),
 (0.0023834086843012997, 'open_il_12m'),
 (0.0023246858038873386, 'open_rv_12m'),
 (0.0018536554313055387, 'delinq_2yrs'),
 (0.0015355498735252582, 'tot_coll_amt'),
 (0.0014392854029285657, 'num_accts_ever_120_pd'),
 (0.0013076785687989013, 'verification_status_Verified'),
 (0.0012549998928549704, 'verification_status_Not Verified'),
 (0.001225139663725757, 'verification_status_Source Verified'),
 (0.0011613710118674968, 'home_ownership_RENT'),
 (0.0010196551596820742, 'application_type_Individual'),
 (0.000874629531509776, 'pub_rec_bankruptcies'),
 (0.0008322360286592995, 'home_ownership_MORTGAGE'),
 (0.0008109239252983619, 'application_type_Joint App'),
 (0.0007611909967212742, 'pub_rec'),
 (0.0007252696663758159, 'home_ownership_OWN'),
 (0.000658200562433588, 'num_tl_90g_dpd_24m'),
 (0.00029581449510710596, 'collections_12_mths_ex_med'),
 (0.0002462230388631975, 'home_ownership_ANY'),
 (7.740235957774729e-05, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [36]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
ee_model = EasyEnsembleClassifier(n_estimators = 100, random_state=1)


ee_model = ee_model.fit(X_train, y_train)
ee_model

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [37]:
y_pred = ee_model.predict(X_test)

In [39]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

1.0

In [38]:
# Display the confusion matrix
print(confusion_matrix(y_test, y_pred))

[[17104     0]
 [    0   101]]

In [40]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00     17104
          1       1.00      1.00      1.00      1.00      1.00      1.00       101

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     17205